# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'newserviceconnection'
    displayName: 'Docker Login'

# - script: |
#     docker pull marcosap31/inventario:v3
#   displayName: 'Docker Pull v3'


- task: Docker@2
 inputs:
   repository: 'marcosap31/inventario'
   command: 'build'
   Dockerfile: 'Dockerfile'  # Asegúrate de tener un Dockerfile en la ubicación correcta
   tags: 'v1'
   displayName: 'Docker Build'

- task: Docker@2
 inputs:
   repository: 'marcosap31/inventario'
   command: 'push'
   tags: 'v1'
   displayName: 'Docker Push'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'appServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp config container set --name 'inventory-api-net' --resource-group 'CMPRG1DEV-RG-APPSRV001' --docker-custom-image-name 'marcosap31/inventario:v3' --docker-registry-server-url 'https://index.docker.io/v1/'
      az webapp restart --name 'inventory-api-net' --resource-group 'CMPRG1DEV-RG-APPSRV001'
  displayName: 'Azure Web App Container Deploy'
  




  
  





  

  